spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        format_sql: true