FROM mysql/mysql-server:8.0.3

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=test_db
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=1234

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]